DROP TABLE IF EXISTS events;
CREATE TABLE events (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  group_id INT NOT NULL,
  title VARCHAR(128) NOT NULL,
  location VARCHAR(128) NOT NULL,
  date VARCHAR(45) NOT NULL,
  time VARCHAR(45) NOT NULL,

  FOREIGN KEY (group_id) REFERENCES studyGroups (id)
);